version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "REPLACE_WITH_YOUR_SECURE_PASSWORD_6699"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - type: bind
        source: ./db_data
        target: /var/opt/mssql
        consistency: consistent

