version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "REPLACE_WITH_YOUR_SECURE_PASSWORD_6699"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - type: bind
        source: ./db_data
        target: /var/opt/mssql
        consistency: consistent

  game:
    build:
      context: ./src
      dockerfile: Dockerfile
      target: game-final
    container_name: iulico_game
    command: /bin/sh -c "dotnet ef database update -c GameContext && dotnet run"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "5187:5187"
    volumes:
      - type: bind
        source: ./logs/game
        target: /app/logs
        consistency: consistent

  account:
    build:
      context: ./src
      dockerfile: Dockerfile
      target: account-final
    container_name: iulico_account
    command: /bin/sh -c "dotnet ef database update -c GameContext && dotnet run"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "9959:9959"
    volumes:
      - type: bind
        source: ./logs/account
        target: /app/logs
        consistency: consistent
