version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'REPLACE_WITH_YOUR_SECURE_PASSWORD_6699'
    ports:
      - '3306:3306'
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/mysql
        consistency: consistent
