version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'REPLACE_WITH_YOUR_SECURE_PASSWORD_6699'
    ports:
      - '3306:3306'
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/mysql
        consistency: consistent
  game:
    build:
      context: ./src
      dockerfile: Dockerfile
      target: game-final
    container_name: iulico_game
    command:
      [
        '/app/wait-for-it.sh',
        'db:3306',
        '--',
        '/bin/sh',
        '-c',
        'dotnet ef database update -c GameContext && dotnet run',
      ]
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
    ports:
      - '5187:5187'
    volumes:
      - type: bind
        source: ./logs/game
        target: /app/logs
        consistency: consistent

  account:
    build:
      context: ./src
      dockerfile: Dockerfile
      target: account-final
    container_name: iulico_account
    command:
      [
        '/app/wait-for-it.sh',
        'db:3306',
        '--',
        '/bin/sh',
        '-c',
        'dotnet ef database update -c GameContext && dotnet run',
      ]
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
    ports:
      - '9959:9959'
    volumes:
      - type: bind
        source: ./logs/account
        target: /app/logs
        consistency: consistent
