version: '3.8'
services:
  game:
    build:
      context: ./src
      dockerfile: Dockerfile
      target: game-final
    container_name: iulico_game
    ports:
      - "5186:5186"
    volumes:
      - type: bind
        source: ./logs/game
        target: /app/logs
        # Ensure the volume is readable and writable by the container
        consistency: consistent

  account:
    build:
      context: ./src
      dockerfile: Dockerfile
      target: account-final
    container_name: iulico_account
    ports:
      - "9958:9958"
    volumes:
      - type: bind
        source: ./logs/account
        target: /app/logs
        # Ensure the volume is readable and writable by the container
        consistency: consistent
